### ISSUE TITLE
Multiple widgets used the same GlobalKey.

### ISSUE THREAD

**Issue by daoxingwudao** [huangjianke/flutter_easyloading#221]
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [LabeledGlobalKey<EasyLoadingContainerState>#c5af6] was used by multiple widgets. The parents of those widgets were different widgets that both had the following description:
  _EffectiveTickerMode(effective mode: enabled)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2883:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#2      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2827:20)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#4      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:2822:36)
#5      BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:2891:6)
#6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2950:11)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3032:8)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:885:19)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#13     _invoke (dart:ui/hooks.dart:148:13)
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#15     _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================

**Comment by ednar28** [comment]
same issue
minimum reproducible example

``` dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      builder: (context, child) {
        return Stack(
          children: [
            EasyLoading.init(),
            child!,
            if (isInDebugMode)
              Positioned(
                right: 0,
                child: const CustomDebugBanner(
                  message: 'Debug',
                  location: BannerLocation.topEnd,
                ),
              )
          ],
        );
      },
      theme: ThemeData(scaffoldBackgroundColor: const Color(0xFFFFFFFF)),
      home: MainScreen(),
    );
  }
```

**Comment by nslogx** [comment]
Verified in v4.0.0. The old shared GlobalKey and OverlayEntry control chain was removed. Overlay keys are now owned by one Host/session, application rebuilds are covered by Cupertino and external-builder regression tests, and a second active Host produces an explicit StateError instead of a duplicate GlobalKey assertion.
