### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by HLQ-Struggle** [huangjianke/flutter_easyloading#27]
您好，异常信息如下：

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3781:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3795:6)
#2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3914:12)
#3      Overlay.of (package:flutter/src/widgets/overlay.dart:256:19)
#4      EasyLoading._show (package:flutter_easyloading/src/easy_loading.dart:338:13)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#4bbd8
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(265.3, 280.0)
  finalLocalPosition: Offset(235.3, 7.0)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
W/IInputConnectionWrapper( 8770): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 8770): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 8770): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 8770): getTextBeforeCursor on inactive InputConnection
W/HiTouch_PressGestureDetector( 8770): Touch pointer move a lot. The moving distance of X is:20.0, limit is:60The moving distance of Y is:63.0, limit is:60
```

以下是我部分代码：
```
import 'package:flutter/material.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart'; 

class UploadArticlePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      debugShowCheckedModeBanner: false,
      home: _UploadArticlePage(),
    );
  }
}

class _UploadArticlePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _UploadArticleState();
}

class _UploadArticleState extends State<_UploadArticlePage> {

  FocusNode _focusNode = FocusNode();
  TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = new TextEditingController();
  }

  @override
  void dispose() { 
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    Widget uploadButtonSection = new Padding(
      padding: EdgeInsets.only(top: 20),
      child: new RawMaterialButton(
          elevation: 2,
          shape: new RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(6.0)),
          ),
          padding: EdgeInsets.all(8),
          splashColor: Colors.white70,
          fillColor: Colors.orange,
          child: new Text(
            '上传',
            textAlign: TextAlign.center,
            style: new TextStyle(
              color: Colors.white,
              fontSize: 18,
            ),
          ),
          onPressed: () {
            String uploadUrl = _controller.text.toString();
            if (uploadUrl.length == 0) {
              hintToast('上传地址不能为空，快去复制吧');
              return;
            }
            if (!uploadUrl.contains('mp.weixin.qq.com')) {
              hintToast('仅支持上传微信公众号链接！');
              return;
            }
            _postUploadArticle(uploadUrl);
          }),
    );

    return Scaffold(
        body: new GestureDetector(
      behavior: HitTestBehavior.translucent,
      onTap: () async {
        FocusScope.of(context).requestFocus(_focusNode);
      },
      child: new Container(
        alignment: Alignment.center,
        margin: EdgeInsets.all(30),
        child: new ListView(
          children: <Widget>[
            uploadButtonSection, 
          ],
        ),
      ),
    ));
  }

  void _postUploadArticle(String uploadUrl) {
    EasyLoading.show();
    HttpManager().post(
        url: uploadArticle,
        params: {
          'timestamp': currentTimeMillis(),
          'token': _userToken,
          'url': uploadUrl
        },
        successCallback: (date) {
          EasyLoading.dismiss();
          hintToast('上传成功～');
          _controller.clear();
        },
        errorCallback: (HttpError err) {
          EasyLoading.dismiss();
          hintToast(err.message);
          _controller.clear();
        },
        tag: requestTag);
  }
}

```

**Comment by HLQ-Struggle** [comment]
请问这个怎么解决呢？

**Comment by HLQ-Struggle** [comment]
大佬，我错了，😅。

设置了根为 FlutterEasyLoading 就好了。

感谢～

**Comment by HLQ-Struggle** [comment]
这个问题又出现了很奇怪啊，到底是啥原因呢？

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Builder:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

The relevant error-causing widget was: 
  MaterialApp file:///Users/HLQ/CodePro/FlutterPro/haozhuan_app/lib/pages/tab/home/make_money.dart:18:16
When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3781:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3795:6)
#2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3914:12)
#3      Overlay.of (package:flutter/src/widgets/overlay.dart:256:19)
#4      EasyLoading._show (package:flutter_easyloading/src/easy_loading.dart:338:13)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by HLQ-Struggle** [comment]
部分代码如下：

```
class MakeMoneyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: _MakeMoneyPage(),
    );
  }
}
```
也的的确确把 FlutterEasyLoading 设置根了。
```
@override
  Widget build(BuildContext context) {
    
    return new Scaffold(
      appBar: appBarSection,
      backgroundColor: ThemeColors.colorMainBackground,
      body: new FlutterEasyLoading(
        child: new ListView(
          scrollDirection: Axis.vertical,
          children: <Widget>[
            apprenticeNumSection,
            moneySection,
            levelSection,
            ruleSection,
            ruleDetailSection,
            todaySection,
          ],
        ),
      ),
    );
  }
```
但是我在 initState 里面调用直接就报错了。
```
@override
  void initState() {
    super.initState();
    _requestDetail();
  }

  void _requestDetail() {
    EasyLoading.show();
    getCacheValue(userToken).then((userToken) {
      HttpManager().post(
          url: getChildDetails,
          successCallback: (data) {
            EasyLoading.dismiss();
          },
          errorCallback: (HttpError error) {
            EasyLoading.dismiss();
          },
          tag: requestTag);
    });
  }
```
求指点指点。

**Comment by huangjianke** [comment]
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return FlutterEasyLoading(
          child: MyHomePage(title: 'Flutter EasyLoading'),
        );
      },
    );
  }
}
```
将 `MaterialApp` 作为根组件试试

**Comment by HLQ-Struggle** [comment]
老哥，还是不行呢，异常如下：

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building _EffectiveTickerMode(effective mode: enabled):
setState() or markNeedsBuild() called during build.

This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: Overlay
  dependencies: [_EffectiveTickerMode]
  state: OverlayState#3e06a(entries: [OverlayEntry#f1e63(opaque: false; maintainState: false), OverlayEntry#b29ea(opaque: false; maintainState: false)])
The widget which was currently being built when the offending call was made was: _EffectiveTickerMode
  effective mode: enabled
The relevant error-causing widget was: 
  FlutterEasyLoading file:///Users/HLQ/CodePro/FlutterPro/xxx_app/lib/pages/tab/home/make_money.dart:20:16
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4167:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4182:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1253:14)
#3      OverlayState.insert (package:flutter/src/widgets/overlay.dart:324:5)
#4      EasyLoading._show (package:flutter_easyloading/src/easy_loading.dart:338:40)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```
部分代码如下：

```
import 'package:flutter/material.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';

class MakeMoneyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      builder: (BuildContext context, Widget child) {
        return FlutterEasyLoading(
          child: _MakeMoneyPage(),
        );
      },
    );
  }
}

class _MakeMoneyPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _MakeMoneyState();
}

class _MakeMoneyState extends State<_MakeMoneyPage>
    with SingleTickerProviderStateMixin { 
    
  @override
  void initState() {
    _requestDetail();
    super.initState();
  }

  void _requestDetail() {
    EasyLoading.show();
    getCacheValue(userToken).then((userToken) {
      HttpManager().post(
          url: getChildDetails,
          params: {
            // ...
          },
          successCallback: (data) {
            EasyLoading.dismiss();
            setState(() {
              _userLevel = data['level'].toString() +
                  " 级" +
                  data['title'].toString(); // 当前级别
              // ...
            });
          },
          errorCallback: (HttpError error) {
            EasyLoading.dismiss();
            hintToast(error.message);
          },
          tag: requestTag);
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: appBarSection,
      backgroundColor: ThemeColors.colorMainBackground,
      body: ListView(
        scrollDirection: Axis.vertical,
        children: <Widget>[],
      ),
    );
  }

Widget appBarSection = new AppBar(
  automaticallyImplyLeading: false,
  backgroundColor: ThemeColors.colorMain,
  centerTitle: true,
  elevation: 1,
  title: new Text(
    '',
    style: new TextStyle(
      color: Colors.white,
      fontWeight: FontWeight.normal,
      fontSize: 18,
    ),
  ),
);

```
大佬指点～

**Comment by huangjianke** [comment]
在 `initState` 中使用的话 需要这样：
```dart
WidgetsBinding.instance.addPostFrameCallback((_) {
  EasyLoading.showSuccess('Great Success!');
});
```

**Comment by HLQ-Struggle** [comment]
感谢大佬～

感谢大哥～

可以啦～谢谢～
