### ISSUE TITLE
App crash after long pressed on textfield

### ISSUE THREAD

**Issue by magicpro97** [huangjianke/flutter_easyloading#36]
**Describe the bug**
App crash after doing long press to show paste option to textfield.

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#1396d](dirty, state: _OverlayEntryWidgetState#bcb2c):
No MediaQuery widget found.

_OverlayEntryWidget widgets require a MediaQuery widget ancestor.
The specific widget that could not find a MediaQuery ancestor was: _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#1396d]
  dirty
  state: _OverlayEntryWidgetState#bcb2c
The ownership chain for the affected widget is: "_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#1396d] ← _Theatre ← Overlay ← Directionality ← FlutterEasyLoading ← App ← LocalizationProvider ← LocalizedApp ← [root]"

Typically, the MediaQuery widget is introduced by the MaterialApp or WidgetsApp widget at the top of your application widget tree.

The relevant error-causing widget was: 
  FlutterEasyLoading file:///Users/ngolinh/work/TCS/MG/mg/lib/app.dart:31:12
When the exception was thrown, this was the stack: 
#0      debugCheckHasMediaQuery.<anonymous closure> (package:flutter/src/widgets/debug.dart:217:7)
#1      debugCheckHasMediaQuery (package:flutter/src/widgets/debug.dart:229:4)
#2      _CupertinoTextSelectionControls.buildToolbar (package:flutter/src/cupertino/text_selection.dart:465:12)
#3      TextSelectionOverlay._buildToolbar (package:flutter/src/widgets/text_selection.dart:588:34)
#4      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:179:34)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

My code:

```
return FlutterEasyLoading(
      child: MultiRepositoryProvider(
        providers: [
          RepositoryProvider<UserRepository>.value(value: userRepository),
          RepositoryProvider<TokenRepository>.value(value: tokenRepository),
        ],
        child: MultiBlocProvider(
          providers: [
            BlocProvider<AppBloc>.value(value: appBloc),
          ],
          child: LocalizationProvider(
              state: LocalizationProvider.of(context).state,
              child: MaterialApp(
                title: translate(I18n.APP_NAME),
                theme: AppTheme.defaultTheme,
                debugShowCheckedModeBanner: false,
                localizationsDelegates: [
                  GlobalMaterialLocalizations.delegate,
                  GlobalWidgetsLocalizations.delegate,
                  localizationDelegate,
                ],
                supportedLocales: localizationDelegate.supportedLocales,
                locale: localizationDelegate.currentLocale,
                onGenerateRoute: routes(),
              ),
            ),
          ),
      ),
    );
```

**Flutter/Dart info**
```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-VN)
    • Flutter version 1.20.1 at /Users/Shared/flutter
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ngolinh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/ngolinh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio
    • Android Studio at /Users/ngolinh/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6720134/Android Studio 4.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 3E380497-2C0E-4305-96A1-0315D2C58D77 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
```

**Screenshots**
https://gyazo.com/6bb59440ec27ebbff3fc59b6aaab7760

**Comment by Hassanmsaid** [comment]
[Just put FlutterEasyLoading under MaterialApp](https://github.com/huangjianke/flutter_easyloading/issues/17#issuecomment-626452507)

**Comment by huangjianke** [comment]
@magicpro97 
you shuould do like this:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return FlutterEasyLoading(
          child: MyHomePage(title: 'Flutter EasyLoading'),
        );
      },
    );
  }
}
```
