### ISSUE TITLE
在最新版flutter中, 无法运行起来

### ISSUE THREAD

**Issue by badboy-tian** [huangjianke/flutter_easyloading#65]
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Overlay(state: OverlayState#7fdd9(entries: [EasyLoadingOverlayEntry#c4209(opaque: false; maintainState: false), EasyLoadingOverlayEntry#9a1c3(opaque: false; maintainState: false)])):
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 552 pos 15: 'textDirection != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Overlay file:///Users/tian/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-2.1.3/lib/src/widgets/loading.dart:62:14
When the exception was thrown, this was the stack: 
#2      new _RenderTheatre (package:flutter/src/widgets/overlay.dart:552:15)
#3      _Theatre.createRenderObject (package:flutter/src/widgets/overlay.dart:509:12)
#4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5491:28)
#5      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6232:11)
...     Normal element mounting (71 frames)
...
```

flutter版本是
```
╰─➤  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1.1)
```

**Comment by badboy-tian** [comment]
```
 FlutterEasyLoading(
        child: MaterialApp(
          routes: {
            "/main": (_) => MainPage(),
          },
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            primaryColor: themeColor,
            accentColor: themeColor,
          ),
          home: ScrollConfiguration(
            behavior: MyBehavior(),
            child: SplashPage(),
          ),
        ),
      ),
```

**Comment by huangjianke** [comment]
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return FlutterEasyLoading(child: child);
      },
    );
  }
}

初始化方式改下

**Comment by badboy-tian** [comment]
ok
